### ISSUE TITLE
CI is currently failing and the only supported python this tests against is Py 3.6 (EOL december)

### ISSUE THREAD

**Issue by graingert** [python-hyper/priority#139]
this project is a dependency of Twisted, which supports 3.6-3.10, so I'd like to: 

- [x] drop support for EOL py2, py3.4 and py3.5, with a commitment to drop 3.6 by Jan 2022
- [x] switch to github actions
- [x] test on py3.6, py3.7, py3.8 and py3.9 (and py3.10 beta) in github actions via tox
- [ ] apply black/pyupgrade/com2ann etc

**Comment by Kriechi** [comment]
I'd be happy to review and merge PRs!

**Comment by graingert** [comment]
@Kriechi looks like this is pretty much all done
