### ISSUE TITLE
Confusing error message when trying to remove stream 0

### ISSUE THREAD

**Issue by alexwlchan** [python-hyper/priority#48]
Consider the following example:

```python
import priority

p = priority.PriorityTree()
p.remove_stream(stream_id=0)
```

If you run this code, you get a confusing error message:

```
Traceback (most recent call last):
  File "zero_stream.py", line 4, in <module>
    p.remove_stream(stream_id=0)
  File "/Users/chana/repos/priority/src/priority/priority.py", line 385, in remove_stream
    parent.remove_child(child)
AttributeError: 'NoneType' object has no attribute 'remove_child'
```

Because stream 0 is really the root of the tree, doesn’t have a parent, and can’t be removed. (At least, I think that’s correct, based on my reading of RFC 7540.)

Although doing this is a bit of an unusual thing to do, the library should still provide a better error message in this case.

(Readers are invited to imagine what sort of pathological tool I might have been using that thinks removing stream 0 is a sensible thing to do.)

**Comment by alexwlchan** [comment]
This also fails:

```python
import priority

p = priority.PriorityTree()
p.insert_stream(stream_id=1)
p.reprioritize(stream_id=0, depends_on=1)
```

with a similar message:

```
Traceback (most recent call last):
  File "zero_importance.py", line 6, in <module>
    p.reprioritize(stream_id=0, depends_on=1)
  File "/Users/chana/repos/priority/src/priority/priority.py", line 362, in reprioritize
    current_stream.parent.add_child(new_parent)
AttributeError: 'NoneType' object has no attribute 'add_child'
```

**Comment by Lukasa** [comment]
Yup, I agree, these should be better. Are you interested in providing a patch?
