### ISSUE TITLE
Dead code in test_priority.py?

### ISSUE THREAD

**Issue by alexwlchan** [python-hyper/priority#61]
There’s a function in `test_priority.py`:

```python
def active_streams_from_unblocked(unblocked):
    """
    Given a collection of unblocked streams, determine which ones are active.
    This applies only to the readme tree at this time, though in future it
    should be possible to apply this to an arbitrary tree.
    """
```

There’s no code associated with the function, and it’s never used anywhere.

@Lukasa Did you have any plans for this function, or is it just dead code?

**Comment by Lukasa** [comment]
Oh god, I probably had plans once, but it was clearly not necessary. Safe to remove. :smile:
